### ISSUE TITLE
Error 16#8180 at comm_load after change a Function Block

### ISSUE THREAD

**Issue by Spawnsen** [rexhip/rexhip#1]
Hello,

first...Thank you very much for the great job.
Your Libary are very amazing.

I have changed at runnig plc the function block and some db blocks.
After that I become the error code 8180 at MB_COMM_LOAD.
I dont have changed the hardware and at an another plc the same programm works.
Is it possible that the comm_load is only load if I stop the plc?
I cant stop the plc and dont know where does the problem come from...

Please help
![image 1](https://user-images.githubusercontent.com/4910440/52664913-850e5c00-2f0a-11e9-80fa-07a08f546852.png)

**Comment by rexhip** [comment]
Hello Spawnsen.

Thanks, I am glad you like it.

For other readers I write the meaning of the error code: 16#8180
"Invalid value for the port ID (wrong address for the communications module)."

You are probably right, rebooting the plc will probably solve the problem. I have two trick you may try to avoid the reboot.

1: Try to toggle the variable "#mb_master_1200_ctrl.conf.comm_load_req".

2: Try to create a new dommy-variable inside the db where the block is located, this will re-init the block.

I have no idea if the suggestion above will work, but it's worth a try. I see the problem related to Siemens, and not particular to my library. Please write back if it doesn't help.

Out of curiosity, what kind of device are you communicating with?

**Comment by Spawnsen** [comment]
Hello rexhip,

today I have the same problem again :-(
I already tried your tricks, but nothing helped. 

For this Issue I will contact the siemens industrial support.

If I have anything new for this issue I contact you.

Thanks

**Comment by rexhip** [comment]
Hi Kèvín.

Thank you for notifying me, I haven't found any solution to this error code
either, except reboot the PLC, and that isn't always possible. It's gonna
be interesting to hear if anyone else has bumped into the same problem. Is
the issue this time for the same plc or is this a different project?

Out of curiosity, do you know how many projects where you have used the
library?

Take care,
Ola

**Comment by Spawnsen** [comment]
Hey Ola,

this is not the same plc.
The issue comes after many DB-inits. I make a function block for a "bitzer CSVH screw"
LINK: [https://www.bitzer.de/us/us/products/screw-compressors/semi-hermetic-frequency-controlled/for-standard-refrigerants/csv-series/](url)
This screw I can only test at the customer and I make the function block via remote connection to the plc.

I have used your library many times, but mostly for reading values and not for critical operations.

If you would have the modbus descrition and the plc code email me: github at kfingas dot de

Thanks Spawnsen

**Comment by KFingas** [comment]
Hey Ola,

I am Spawnsen and this is my second account.

I have found something about the modbus fc from siemens.

In your lib you use the "MB_COMM_LOAD" and "MB_MASTER" and "MB_SLAVE". 
With the "Modbus_Comm_Load", "Modbus_Master" and "Modbus_Slave" it is possible to read the complete register table from 9999 to 65535. With the other one this is not possible?! (this is my information)
Here the Link from Siemens: https://support.industry.siemens.com/cs/de/en/view/109474481
![image](https://user-images.githubusercontent.com/92255819/167856409-a810e1dc-88c9-4747-aebf-f1c190a22a1d.png)
Sry for german text...

I have changed the block in your lib, but can´t upload without plc stop.
Do you think this will work?
The only thing I have changed is the "MB_DB" connection from comm_load to master. this have changed in the function from siemens.

For my application, I must read IR 12003 or IR 14002 and it dont work at the moment.
Is this possible with an special mode in your lib?

Thanks Kevin

**Comment by rexhip** [comment]
Hi

I haven't done a good job on documented this, but for accessing input
register above 9999, you need to use «mb_rtu1500_ctrl» , instead of
«mb_rtu1200_ctrl». Then simply use «#mb_query.c.read.input_reg», and assign
the value (12003) to data_addr. «mb_rtu1500_ctrl» actually work for both
1200-series and 1500-series, but it use more memory then «mb_rtu1200_ctrl».
For holding register above 9999, you may use either of them.

Please ask if you have further questions.

- Ola

**Comment by KFingas** [comment]
Hey,

okay that´s a good information.
I've been thinking the whole time that's the difference between the S7-1200 and the S7-1500. Maybe I didn't read your instructions carefully enough :D
Next week I have time to test this and then I use the «mb_rtu1500_ctrl»

Thanks
Kevin
