### ISSUE TITLE
Conditional queries

### ISSUE THREAD

**Issue by pynista** [rexhip/rexhip#12]
I used Rexhip to control the frequency converter. Everything works great. Thank you!

However, I can't figure out if conditional queries can be used safely. 

What I mean is this.
For example, we have scales. The scales must be calibrated by pressing the "Calibrate" button on the HMI panel. 
Accordingly, it is necessary to record the control word for calibration once only when the operator presses the button "Calibrate".
The file "queries.md" says the following:

> "//When then number of queries changes with different plc-scan, 
> // like above. Then the library gets a little "hiccup". If the 
> // if-statement changes rapidly, then the example can break part
> // of modbus application."

So, it turns out that when using conditional queries we get non-deterministic program behavior?

**Comment by rexhip** [comment]
Hi Pynista.

In the example you mention above with a button in the HMI, there is no problem to do a conditional query. By «rapidly» it means a condition that changes more frequently then every two seconds or so, then it might be a problem. So it's really more a rear edge scenario.

The order of query executions becomes non-deterministic if there are conditional queries. E.g. the query after the condition might be executed twice before the loop continue, or a query might be skipped, but then be executed on the next round. If there is a need for deterministic execution order, then there is a example in the library that might be followed.

```pascal
// A simple example.

// Other queries goes here ...
// It's best to have conditional queries after other queries.
IF #start_calibration THEN
    #mb_query(
          mode := #mb_query.c.write.holding_reg,
          data_addr := 12345,                            
          data_ptr := #data );
    IF #mb_query.Done THEN
        #start_calibration := false ;
    END_IF;
ELSE
    // Or other queries might go here ...
END_IF;
```

I hope my answer was understandable, please ask if you have other questions.

**Comment by rexhip** [comment]
Just to be clear, it's safe to use conditional queries. I recommand to put them after other queries inside station blocks.
