### ISSUE TITLE
Issue reading from input register 

### ISSUE THREAD

**Issue by xGuysOG** [rexhip/rexhip#13]
System details:
Its a Simatic s7-1200
CPU is 1212C DC/DC/Rly
With a CB 1241 (RS485)

here is my code:
![image](https://github.com/user-attachments/assets/93d6540a-4ba2-4b75-a44a-ff991621793a)

im met with a 8188 somehow which im suppoing is "Invalid Mode specified for broadcast request"
![image](https://github.com/user-attachments/assets/302461bb-d8ad-4f15-a9de-d41cac3bf899)

im trying to read input register (3003) in hex aka 12291, ive attempted that and 12292 which is what you can see in my screenshot

i dont understand how we can end up at the wrong mode here.

**Comment by rexhip** [comment]
Try use mb_rtu1500_ctrl instead of mb_rtu1200_ctrl.

Due to some siemens internals, the 1200-block can not handle register address above 9999 for input registers. The disadvantage of using 1500 block is that it uses more memory.

**Comment by xGuysOG** [comment]
> Try use mb_rtu1500_ctrl instead of mb_rtu1200_ctrl.
> 
> Due to some siemens internals, the 1200-block can not handle register address above 9999 for input registers. The disadvantage of using 1500 block is that it uses more memory.

I attempted the 1500 and does pull the data out, it just somehow takes 10 seconds for a 6 lenght pull of int. Which seems insane to me, ive made a short video to show it.
https://www.youtube.com/watch?v=kIHj6OGl_6k

**Comment by rexhip** [comment]
Yes it should only take a few milliseconds. I am unsure about the code in the video, have you tried with the rexhip library? mb_rtu1500_ctrl is a block that comes along

**Comment by xGuysOG** [comment]
@rexhip I am so so so sorry, ive attached the correct video, i dont know how i fucked up so badly.
https://youtu.be/SkBc6NB1oC0

**Comment by xGuysOG** [comment]
The code itself is pretty much the same i just replaced 1200 with 1500:
![image](https://github.com/user-attachments/assets/aadaf46f-a4ef-486c-a11c-f73c8b7141ee)

**Comment by rexhip** [comment]
Each query will need to plc-cycles, one for insert the query, one other for receiving the result. When you have 1000ms intervall, this will add up to 2 seconds.

10 seconds as you mentioned above, I can't explain for you. If you like to dive deeper, you can hook up RS-485/RS-232 converter to the bus, and look at the telegrams being sent and received.

Tip: When you debug, I recommend looking at the #sb.log variables inside the station blocks.

Good luck debugging :)

**Comment by xGuysOG** [comment]
> Each query will need to plc-cycles, one for insert the query, one other for receiving the result. When you have 1000ms intervall, this will add up to 2 seconds.
> 
> 10 seconds as you mentioned above, I can't explain for you. If you like to dive deeper, you can hook up RS-485/RS-232 converter to the bus, and look at the telegrams being sent and received.
> 
> Tip: When you debug, I recommend looking at the #sb.log variables inside the station blocks.
> 
> Good luck debugging :)

Then how would i go about polling data every 1s, if they need extra for the cycles?, other then polling every 500ms.
Sorry im still a little new to PLC.

**Comment by rexhip** [comment]
Yes, you may let the interrupt run every 500ms. But in my opinion I would say a better approach is to let the modbus routine run together with the rest of your program in "Main".

**Comment by xGuysOG** [comment]
> Yes, you may let the interrupt run every 500ms. But in my opinion I would say a better approach is to let the modbus routine run together with the rest of your program in "Main".

And then use a TON or another timer?, 
When looking around i was told to use a sequence like system to just queue based on timings and information, so for example if i need to tell the machine to run certain get and sets with some delay and make sure they don't happen at the exact same time id do below:
`            
            "MB_COMM_LOAD_DB"(REQ := #intial,
                              "PORT" := "Local~CB_1241_(RS485)",
                              BAUD := 115200,
                              PARITY := 2,
                              FLOW_CTRL := 0,
                              RTS_ON_DLY := 0,
                              RTS_OFF_DLY := 0,
                              RESP_TO := 1000,
                              DONE => "Data_block_2"."Load Done2",
                              ERROR => "Data_block_2"."Load Error2",
                              STATUS => "Data_block_2"."Load Status2",
                              MB_DB := "MB_MASTER_DB");
            IF "flag_data".flag_going_up THEN
                
                CASE #counter OF
                    0:
                        "MB_MASTER_DB"(REQ := "Data_block_2"."Load Done2",
                                       MB_ADDR := 2,
                                       MODE := 0,
                                       DATA_ADDR := 420500,
                                       DATA_LEN := 1,
                                       DONE => "Data_block_2"."Master Done2",
                                       BUSY => "Data_block_2"."Master Busy2",
                                       ERROR => "Data_block_2"."Master Error2",
                                       STATUS => "Data_block_2"."Master Status2",
                                       DATA_PTR := "Data_block_2"."5013");
                    1:
                        "MB_MASTER_DB"(REQ := "Data_block_2"."Load Done2",
                                       MB_ADDR := 2,
                                       MODE := 0,
                                       DATA_ADDR := 420501,
                                       DATA_LEN := 1,
                                       DONE => "Data_block_2"."Master Done2",
                                       BUSY => "Data_block_2"."Master Busy2",
                                       ERROR => "Data_block_2"."Master Error2",
                                       STATUS => "Data_block_2"."Master Status2",
                                       DATA_PTR := "Data_block_2"."5014");
                    4:
                        "MB_MASTER_DB"(REQ := "Data_block_2"."Load Done2",
                                       MB_ADDR := 2,
                                       MODE := 0,
                                       DATA_ADDR := 420492,
                                       DATA_LEN := 1,
                                       DONE => "Data_block_2"."Master Done2",
                                       BUSY => "Data_block_2"."Master Busy2",
                                       ERROR => "Data_block_2"."Master Error2",
                                       STATUS => "Data_block_2"."Master Status2",
                                       DATA_PTR := "Data_block_2"."500B");
                    5:
                        "MB_MASTER_DB"(REQ := "Data_block_2"."Load Done2",
                                       MB_ADDR := 2,
                                       MODE := 0,
                                       DATA_ADDR := 420490,
                                       DATA_LEN := 1,
                                       DONE => "Data_block_2"."Master Done2",
                                       BUSY => "Data_block_2"."Master Busy2",
                                       ERROR => "Data_block_2"."Master Error2",
                                       STATUS => "Data_block_2"."Master Status2",
                                       DATA_PTR := "Data_block_2"."5009");
                        
                    9:
                        "MB_MASTER_DB"(REQ := "Data_block_2"."Load Done2",
                                       MB_ADDR := 2,
                                       MODE := 0,
                                       DATA_ADDR := 420493,
                                       DATA_LEN := 1,
                                       DONE => "Data_block_2"."Master Done2",
                                       BUSY => "Data_block_2"."Master Busy2",
                                       ERROR => "Data_block_2"."Master Error2",
                                       STATUS => "Data_block_2"."Master Status2",
                                       DATA_PTR := "Data_block_2"."500c");
                    11:
                        "MB_MASTER_DB"(REQ := "Data_block_2"."Load Done2",
                                       MB_ADDR := 2,
                                       MODE := 0,
                                       DATA_ADDR := 420494,
                                       DATA_LEN := 1,
                                       DONE => "Data_block_2"."Master Done2",
                                       BUSY => "Data_block_2"."Master Busy2",
                                       ERROR => "Data_block_2"."Master Error2",
                                       STATUS => "Data_block_2"."Master Status2",
                                       DATA_PTR := "Data_block_2"."500d");
                END_CASE;
                IF "Data_block_2"."Master Done2" OR "Data_block_2"."Master Error2" THEN
                    #counter := #counter + 1;
                END_IF;
                IF #counter >= 12 THEN
                    "flag_data".is_flag1_up := true;
                    "flag_data".flag_going_up := false;
                END_IF;
                
            END_IF;`
           
           How would i go about doing this from my main? The original creation of the counter for sequence was just to not call the same modbus main and therefor leaving the port open to only be called when not in use, i hope my statement makes sense, im sorry if this is asking for too much info / help, im just trying to get the right use out of your libary as it seems so much better then the default.

**Comment by rexhip** [comment]
If you use the rexhip library there is no timers or sequence to think about, everything is handled by the library. Just do as you did in your first post.

You may also look at the start example that comes along the library.

Good luck.

**Comment by xGuysOG** [comment]
> If you use the rexhip library there is no timers or sequence to think about, everything is handled by the library. Just do as you did in your first post.
> 
> You may also look at the start example that comes along the library.
> 
> Good luck.

I see, if i were to have a constant pulling occurring from the "Main" like this:
![image](https://github.com/user-attachments/assets/fce0518b-4799-4e11-ae0a-efda63f69b0b)
Can i then in a seperate function that gets called in the CyclicInterupt, call a write function?
![image](https://github.com/user-attachments/assets/d0488387-6645-4970-8060-bad010c2313c)

Like does that get added to the queue, or do i have to do some managing of calls since its happening in a different function block getting called from elsewhere?

**Comment by rexhip** [comment]
No, that is not possible, all query should be called from the same OB, I recommend to invoke the modbus program from main. 

You should not combine the Rexhip library with Siemens native modbus blocks.

Please, see the start example, and then try adapt a station block to your need. It is possible to have conditional queries.

**Comment by xGuysOG** [comment]
> No, that is not possible, all query should be called from the same OB, I recommend to invoke the modbus program from main.
> 
> You should not combine the Rexhip library with Siemens native modbus blocks.
> 
> Please, see the start example, and then try adapt a station block to your need. It is possible to have conditional queries.

Yeah i will just use conditional setups, i would never combine the 2 libarys, i just meant that i wanted to call a write with rexhip in another function block if it was possible, while i had a constant polling action going on in another function block.

**Comment by rexhip** [comment]
Yes, that is possible.

**Comment by rexhip** [comment]
Try change the datatype of flagPos from usint to uint

**Comment by rexhip** [comment]
Did it help to change the datatype of the variable? The data type in the plc need to match the register you are querying.
