### ISSUE TITLE
Compilation error using Modbus RTU 1200

### ISSUE THREAD

**Issue by cardinal-tom** [rexhip/rexhip#5]
Hi, I'm trying to use your modbus example project to send some text to an LCD but it won't compile successfully. When using the modbus_rtu_1200 function block, I get an error when compiling which is as follows: "The data type mb_query of the actual parameter does not match the data type mb_query_1 of the formal parameter mb_query". I've attached a screenshot comparing the library block with my test block.

Changing the data type to "mb_query_1" here results in the opposite compilation error, i.e. "The data type mb_query_1 of the actual parameter does not match the data type mb_query of the formal parameter mb_query"

Looking at the control library blocks, mb_rtu1200_ctrl defines the InOut variable mb_query using datatype "mb_query_1" and mb_tcp_ctrl as "mb_query".

Am I doing something wrong? I'm using version 3.4.1 of your library, V16 update 4, and a 1214C PLC on firmware 4.4 - there is a 4.5 firmware update available but I wouldn't have thought that would be the issue here.

![2021-05-19 12_48_39-Greenshot](https://user-images.githubusercontent.com/63024021/118808522-837a2e00-b8a1-11eb-8ce9-b893ec1665c8.png)
![2021-05-19 12_43_42-Greenshot](https://user-images.githubusercontent.com/63024021/118808526-8412c480-b8a1-11eb-9702-00ffce287e3c.png)

**Comment by rexhip** [comment]
Hi cardinal-tom.

I am in the prosess of moving to a new apartment at the moment. Is it okay to wait some days? It looks you haven't done anything wrong, but I will take a deeper look in to it.

Kind regards,
Ola

**Comment by cardinal-tom** [comment]
No worries, thanks for letting me know and best of luck with the move.

Tom

**Comment by rexhip** [comment]
Hi Tom.

I may take a look at it through a screen viewer software, like TeamViewer, Teams, Skype, etc. If you are interested you can use the contact form link, on the bottom of the front page.

https://sn7.no/contact/rexhip

Looking forward to hear from you.

**Comment by cardinal-tom** [comment]
Thanks for your help Ola, for anyone reading this the fix will be in the next minor version.

Tom
