### ISSUE TITLE
Expose parity as an input parameter in CTRL FBs

### ISSUE THREAD

**Issue by gitneko** [rexhip/rexhip#7]
I've been checking out this library to use this for a project where I have multiple modbus RTU devices. They all operate luckily on parity even, however I've already had different parities before (the projects weren't with Siemens however).

However the Modbus RTU CTRL FBs don't expose the parity as a parameter so it could be adapted, but instead it's an element in a FB struct. The FB struct elements however can't be accessed from the program, thus the parity can't be changed without importing the FB into the program and changing the value manually.

So I'd like to propose to expose the parity as an input parameter on the FB, just like you've already exposed operating mode and baud rate. This will make things a lot simplier and reusable, regardless of how vendor devices operate (since some have fixed modbus settings).

While most vendor devices use changable parity or already use even, it would still make it easier to expose the parity, so all devices can be simple integrated.

**Comment by rexhip** [comment]
Hi gitneko

Thank you for finding interest in the library, I like to get feedback and see that other people has dug in to the code.

The modbus specification for serial line v1.02 state on page 34 that «even» should be the default parity. I believe life would be easier for everyone if everyone just agree to use «even» parity for  serial modbus. 

I reflected both forth and back on the decision to put the parity-parameter inside that conf-struct. On one hand I like to encourage people to use the default of the specification. On the other hand, and as you argue, the parity might be impossible to change for some devices, and for those people I made life slightly harder. Changing parity is not to hard though, just add one line in front of the controller, see bellow:
```
#mb_rtu1200_ctrl.conf.parity := 0 ;  // 0=None , 1=odd, 2=even
// In ladder use the move instruction

#mb_rtu1200_ctrl(hardware_id := "Local~CB_1241_(RS485)",  
                 baud := 19200, // bps                
                 mb_query := #mb_query ) ; 
```
For baud rate and operation mode, these parameters need to be changed from time to time for good reasons, that is why they are exposed as input parameters.

This is how I see it, if you have other views or arguments I will like to hear them. 

I will answer your other feature request as soon as possible.

Thank you again, for giving your feedback.

**Comment by gitneko** [comment]
Hello

Thank you for getting back to me.

I agree that we should use sane defaults - here being the modbus specification defaults. However since there's a choice - regardless of whether of all agree on it or not - the choice needs to be clear to the user in case they use the library. We cannot assume that everyone uses the default that is written on a paper as "SHOULD USE". As long as it's not "MUST USE" there's bound to be a need to change the modbus parameters.

The choice isn't made easy since they need to open the FB to see that they can change parity and stopbits somewhere in there (no idea where you'd change databits, thankfully everyone has used 8 databits so far, I'd guess directly on the RS485 module). "Life slighty hard" is a bit too tame said, considering consumers have to to open the FB and actually read and see where they can change it.

So I'd argue that currently hidden modbus parameters should be made input parameters for consumers of this library. Directly accessing specific variables inside of a FB or even inside FB of another FB is bad and bound to break. This is to be equated like an internal API. Otherwise this needs to be properly documented and the regular guarantees of a public API must be granted, however it's still less ideal.

I've created for my own purpose temporarily a wrapper around the control FBs and exposed the modbus parameters, so I can currently easily work with different devices. However I'd like to see the control FBs evolving.

Again, thank you for taking the time to create this library and think about the issue.

**Comment by rexhip** [comment]
I believe giving every, or too many options as an input parameter, looks confusing. I believe a good design should make user interfaces as simple as possible, and sometimes that implies making some choices for the user. I may be wrong about this, but I think we should be bold and stop making parity and stop bits, options for the user, because there is no benefit in choosing one over the other. I like this library to be in front in this cause.

The PID-block that comes along with TIA-portal, have some configuration inside structs in static variables, so I don’t think that approach is too unfamiliar for Siemens users. But I agree, when users are forced to change stop bits for example, it is too complicated, because there is no documentation that describes how to do it. 

I decided to keep the current input parameters, but I will do a better job on documentation for changing these settings. I hope my decision is not too disappointing, despite your effort. I do need input also in the feature. Btw, happy new year !

**Comment by gitneko** [comment]
Thank you very much for your response. As long as this gets properly documented, this is fine by me. :)
